Add ci to envoy-private
* [Datadog CI] fix missing --load docker option

* ci: Update service account for gitlab ci runners (#760)

This should fix the error we're seeing now

```
ERROR: Job failed (system failure): prepare environment: setting up build pod: pods "runner-xzxvyd9d-project-3351-concurrent-1" is forbidden: error looking up service account gitlab-runner-envoy/envoy-private: serviceaccount "envoy-private" not found. Check https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading for more information
```

example job: https://gitlab.ddbuild.io/DataDog/envoy-private/-/jobs/423302523

Also adds the `specific:true` tag to the `deliver-ci` and `envoy-image`
jobs as this repo should have its own CI runners

fix CI (#959)

[FCP-1208] Add fips compliance labels (#962)

envoy-private: build fips image on top of fips base image (#964)

campaigner for envoy-private (#960)

Upgrade ddsign client version

ci: add check on format and pre-commit (#976)

ci: fix protobuf generation from laptop (#985)

chore: fix CI

Changes:
  - Update base docker image on `f4a881a1205e8e6db1a57162faf3df7aed88eae8`.
  - Update ci image used by Gitlab.
  - Enforce clang configuration for building envoy

Upgrade ddsign client version

envoy-build: Update our image to ubuntu 24

Signed-off-by: William Dauchy <william.dauchy@datadoghq.com>